services:
  # Radarr
  radarr:
    container_name: radarr
    volumes:
      - ${CONTAINER_DIR}/radarr/config:/config
      - ${MEDIA_DIR_MOVIES}:/movies
      - ${DOWNLOAD_DIR}:/downloads
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    networks:
      - internal
      - proxied
    restart: unless-stopped
