services:
  # Sonarr
  sonarr:
    container_name: sonarr
    volumes:
      - ${CONTAINER_DIR}/sonarr/config:/config
      - ${MEDIA_DIR_TV}:/tv
      - ${DOWNLOAD_DIR}:/downloads
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    networks:
      - internal
      - proxied
    restart: unless-stopped
