services:
  kodi-headless:
    container_name: kodi-headless
    volumes:
      - ${CONTAINER_DIR}/kodi-headless/config:/config/.kodi
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    depends_on:
      - kodi-mariadb
    networks:
      - proxied
      - internal
    restart: unless-stopped
  kodi-mariadb:
    container_name: kodi-mariadb
    volumes:
      - ${CONTAINER_DIR}/kodi-mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - internal
    restart: unless-stopped
