services:
  # Lidarr
  lidarr:
    container_name: lidarr
    volumes:
      - ${CONTAINER_DIR}/lidarr/config:/config
      - ${MEDIA_DIR_MUSIC}:/music
      - ${DOWNLOAD_DIR}:/downloads
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    restart: unless-stopped
