services:
  gazee:
    container_name: gazee
    volumes:
      - ${CONTAINER_DIR}/gazee/config:/config
      - ${CONTAINER_DIR}/mylar/config:/mylar
      - ${MEDIA_DIR_COMICS}:/comics
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    restart: unless-stopped
