services:
  # Heimdall
  heimdall:
    labels:
      - traefik.backend=heimdall
      - traefik.frontend.rule=Host:heimdall.${DOMAIN}
      - traefik.docker.network=proxied
      - traefik.port=80
    expose:
      - 80
      - 443
