services:
  # NZBGet
  nzbget:
    container_name: nzbget
    volumes:
      - ${CONTAINER_DIR}/nzbget/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    networks:
      - internal
      - proxied
    restart: unless-stopped
