services:
  glances:
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONTAINER_DIR}/glances/config:/glances/conf
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - GLANCES_OPT=-w
    networks:
      - internal
      - proxied
    pid: host
    restart: unless-stopped
