services:
  glances:
    labels:
      - traefik.backend=glances
      - traefik.frontend.rule=Host:glances.${DOMAIN}
      - traefik.docker.network=proxied
      - traefik.port=61208
    expose:
      - 61208
      - 61209