services:
  # Jackett
  jackett:
    labels:
      - traefik.backend=jackett
      - traefik.frontend.rule=Host:jackett.${DOMAIN}
      - traefik.docker.network=proxied
      - traefik.port=9117
    expose:
      - 9117
