services:
  # Jackett
  jackett:
    container_name: jackett
    volumes:
      - ${CONTAINER_DIR}/jackett/config:/config
      - ${DOWNLOAD_DIR}/jackett/blackhole:/downloads
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    networks:
      - internal
      - proxied
    restart: unless-stopped
