services:
  # Headphones
  headphones:
    container_name: headphones
    volumes:
      - ${CONTAINER_DIR}/headphones/config:/config
      - ${MEDIA_DIR_MUSIC}:/music
      - ${DOWNLOAD_DIR}:/downloads
      - ${SHARED_DIR}:/shared
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    networks:
      - internal
      - proxied
    restart: unless-stopped
