services:
  # NZBHydra
  hydra:
    labels:
      - traefik.backend=hydra
      - traefik.frontend.rule=Host:hydra.${DOMAIN}
      - traefik.docker.network=proxied
      - traefik.port=5076
    expose:
      - 5076
